### PR TITLE
Update GenerateFromDb.php to support PostgreSQL.

### PR DESCRIPTION
**Pull request by tortuetorche**
Can you test if MySQL is always OK with this patch, please ?
And if it is, can you also merge this patch to the `Gadoma-extendedmodels` branch ?

Thank you !

### CODE REVIEW

**Comment by XCMer** [comment]
I believe you will have to re-send the pull request targeting the Gadoma-extendedmodels branch (since GitHub won't allow me to change that from this end). Thanks.

**Comment by tortuetorche** [comment]
OK, but do you plan to merge my pull request into the `master` branch ?

**Comment by XCMer** [comment]
I sure will do that. The Gadoma-extendmodels branch will be merged to master once I've written tests for it and verified its working. Both of these changes will be a part of the next version.

**Comment by Gadoma** [comment]
Hey guys, 
thanks for the interet into the extendedmodels branch. After the initial Pull Request I had made some further enhancements to my fork (but still not all new features are 100% completed), but in general the code needs a little tidy-up, proper documentation and tests. Unfortunately I am totally absorbed with my regular job untill at least half of september so I wont be able to prepare my fork for another PR. But still I'll try to help @XCMer with preparing the gadoma-extendedmodels branch to be merged into the master repository. 

Anyway, I think that Larry4 is a great great library, I will surelly be using it in future because it substantially speeds up the design&development process. (yep, you can for example quicky redesign your schema and have the basic implementation autogenerated in eyes blink) 

If your into it @XCMer , it'd be good to sit down and think of the best way to enhance Larry. Great idea to cover the PgSQL area, but I myself dont use much. My idea is to give Larry further autogenerate functionality, as in the extended models :) 

What do you think about the general idea ?

**Comment by XCMer** [comment]
I ran into similar work commitment problems. However, I am keen on working on the tests and tidying up of the extendedmodels branch. It'd be great to have other auto-generate functionalities as well. If any idea clicks, I'll just create a new branch for it, so that people can test and contribute to it in isolation until it's ready.

**Pull request merged**
