### PR TITLE
Enabling Larry Four to generate extended models (suitable for automatic model validation)

### PR DESCRIPTION
**Pull request by Gadoma**
This branch can generate models extending base class different than Eloquent, automatiaclly using additional namespaces you specify, and adding a validation rules array stub.

In a handy config file you can set 
- if you want to automatically extend generated models, 
- which models to ommit (use default base class), 
- what should be the extended and default base class and additional namespaces for your models 
- if you want to add the validation stubs

By default, you'll have: 

```
class Modelname extend Eloquent {
```

Now you can instantly have:

```
use Namespace\Subnamespace\Something; 
class Modelname extends Something
{
    public static $rules = array();
```

### CODE REVIEW

**Comment by Gadoma** [comment]
In the last commit further "extendedmodels" functionality was introduced. Larry Four can now generate different additional fields and functions in the models (fillable, guarded, hidden). The model validation rules array is prefilled with fields and rules which are created based on config. New configuration options for Ardent (laravelbook/ardent) and Sluggable (cviebrock/eloquent-sluggable) now also available for generation. The configuration has been also extended and split into two separate files.

Current minor TODOs are:
- update the Readme.md file
- extend validation and sluggification default configs
- prepare updated Tests :)

Next major functionality TODO is
- support for generating additional functionality for relationships
- support for generating FrozenNode/Laravel-Administrator model configuration stubs

**Comment by XCMer** [comment]
Thanks for the effort. I'll review it as soon as possible. On a side note, you can also create a CONTRIBUTORS.md file and add your name to it.

**Comment by Gadoma** [comment]
Hello, I created an [issue repository](https://github.com/Gadoma/larry-four-generator/issues) on my fork jus to point out the ideas listed in my comment above. If you merge the new stuff into your master branch a proper road map / issue list can be created.

**Comment by XCMer** [comment]
I've done a manual merge and pushed your changes to a new branch named "Gadoma-extendedmodels". You can send your subsequent pull requests to this branch and I'll merge this via GitHub directly.

**Comment by XCMer** [comment]
Closing this since this branch was manually merged.

**Comment by sanketsahu** [comment]
Is this merged? How can I use Ardent with Larry generator? Please help.

**Comment by Gadoma** [comment]
To use the up to date Gadoma-extendedmodels functionality, while having all the current bug fixes from XCMer master branch incorporated,  try it out on my fork https://github.com/Gadoma/larry-four-generator/tree/Gadoma-extendedmodels . I will be requesting another pull here soon.

Best regards,
Gadoma

**Pull request closed without merging**
